meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: graphite-nozzle-z1
    templates:
      - name: graphite-nozzle
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "please set graphite-nozzle networks" ))
 
networks: (( param "please set networks" ))

properties:
  graphite_nozzle:
    doppler_endpoint: "wss://doppler.10.244.0.34.xip.io:443"
    uaa_endpoint: "https://uaa.10.244.0.34.xip.io"
    subscription_id: "firehose"
    statsd_endpoint: "10.244.11.2:8125"
    statsd_prefix: "mycf."
    prefix_job: true
    username: "admin"
    password: "admin"
    skip_ssl_validation: true